const KEY_ACCOUNT_INTEGRATION_BUTTON = 'ACCOUNT_INTEGRATION_BUTTON_KEY';
const KEY_KAKAO_LOGIN_BUTTON = 'KAKAO_BUTTON_KEY';
const KEY_APPLE_LOGIN_BUTTON = 'APPLE_BUTTON_KEY';
const KEY_PASS_CERTIFICATION_BUTTON = 'PASS_CERTIFICATION_BUTTON_KEY';
