/// Membership Route Defined
const String ROUTE_LOGIN = 'LOGIN';
const String ROUTE_ACCOUNT_INTEGRATION = 'ACCOUNT_INTEGRATION';
const String ROUTE_KAKAO_LOGIN = 'KAKAO_LOGIN';
const String ROUTE_APPLE_LOGIN = 'APPLE_LOGIN';
const String ROUTE_PASS_CERTIFICATION = 'PASS_CERTIFICATION';
const String ROUTE_REGISTER_INTEGRATION = 'REGISTER_INTEGRATION';
const String ROUTE_REGISTER_NEW = 'REGISTER_NEW';
const String ROUTE_REGISTER = 'REGISTER';
const String ROUTE_REGISTER_USER_INFO = 'REGISTER_USER_INFO';